services:
  - type: web
    name: sign-language-api
    runtime: python
    repo: https://github.com/Usman-debug-coder/sign-language-backend.git
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1 --threads 4
    envVars:
      - key: WHISPER_MODEL
        value: tiny
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.10.12"
