services:
  - type: web
    name: sign-language-api
    runtime: docker
    repo: https://github.com/Usman-debug-coder/sign-language-backend.git
    plan: free
    envVars:
      - key: WHISPER_MODEL
        value: tiny
      - key: ALLOWED_ORIGINS
        value: "*"
